# Generated by Django 2.2.5 on 2019-09-19 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0005_valid_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='goods_store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Seller.LoginUser'),
        ),
    ]
